name: pictus
description: "A new Flutter package project."
version: 0.0.1
homepage: https://tally.city/

environment:
  sdk: '>=3.5.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  camera: ^0.11.0+2
  crop_your_image: ^1.1.0
  flutter:
    sdk: flutter
  image: ^4.2.0
  image_painter: ^0.7.1
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
# flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

